name: Automatically update and run pre-commit hooks

on:
  # Run weekly at seventeen minutes past midnight (hopefully this plays nice with the infrastructure).
  schedule:
    - cron: '17 0 * * 1'

  # Also enable running manually.
  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set the name of the branch for these changes
        id: branch
        run: echo "::set-output name=branchname::pre-commit-autoupdate"

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install pre-commit
        run: pip install pre-commit

      - name: ${{ github.workflow }}
        run: |
          pre-commit autoupdate
          until pre-commit run --all-files; do
            git diff --quiet && {
              echo One or more pre-commit hooks failed but re-running will not result in changes.
              exit 1
            }
            echo One or more pre-commit hooks failed and there are changes to the repository.
            echo -e "\e[1mRe-running pre-commit hooks...\e[0m"
            git add -A
          done

      - name: Create pull request
        id: pr
        # Don't use release tags for actions, except from the 'actions' organisation:
        # https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
        # Commit is equivalent to release tag v3.6.0.
        uses: peter-evans/create-pull-request@45c510e1f68ba052e3cd911f661a799cfb9ba3a3
        with:
          branch: ${{ steps.branch.outputs.branchname }}
          commit-message: ${{ github.workflow }}
          title: ${{ github.workflow }}
          body: Update pre-commit hooks and run them on the entire code base.
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
